/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Usuario
 */
public class StartFrame extends javax.swing.JFrame {

    /**
     * Creates new form StartFrame
     */
    MarioServer server;
    int numJugador;
    String nick;
    int currentPlayer = 1;
    Color color;
    LinkedList<JButton> botones;
    int configurados = 0;
    Client cliente;
    public JButton[] opcionArray = new JButton[10];
    private LinkedList<String> coloresElegidos;
    boolean lastPlayer = false;
    public StartFrame() throws IOException {
        botones = new LinkedList();
        //cliente = new Client(this);
        coloresElegidos = new LinkedList();
       // cliente.connect();
        initComponents();
//        btRojo.setBackground(Color.red);
//        btNaranja.setBackground(Color.orange);
//        btAzul.setBackground(Color.blue);
//        btAmarillo.setBackground(Color.yellow);
//        btCeleste.setBackground(Color.cyan);
//        btBlanco.setBackground(Color.white);
//        btMorado.setBackground(new Color(138,43,226));
//        btNegro.setBackground(Color.black);
//        btVerde.setBackground(Color.green);
//        btRosado.setBackground(Color.pink);
//        botones.add(btRojo);
//        botones.add(btNaranja);
//        botones.add(btAzul);
//        botones.add(btAmarillo);
//        botones.add(btCeleste);
//        botones.add(btBlanco);
//        botones.add(btMorado);
//        botones.add(btNegro);
//        botones.add(btVerde);
//        botones.add(btRosado);
        initButtons();
    }

    public void setCliente(Client cliente) {
        this.cliente = cliente;
    }
    
    private void initButtons(){
        for (int i = 0; i < opcionArray.length; i++){
            opcionArray[i] = new JButton();
            opcionArray[i].setActionCommand(i + "");
            opcionArray[i].setBackground(chooseColor(i));
            jPanel1.add(opcionArray[i]);
            opcionArray[i].setBounds(0, i * 40, 200, 40);
            opcionArray[i].addActionListener(new ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    
                    buttonPressed(evt);
                }
                });
        }
    }
    
    public void buttonPressed(java.awt.event.ActionEvent evt){
        JButton botonTemp = (JButton)evt.getSource();
        
        
        if(numJugador == currentPlayer) {
            color = botonTemp.getBackground();
            //currentPlayer++;
            botonTemp.setEnabled(false);
            try {
                this.mandarColor(color);
            } catch (IOException ex) {
                Logger.getLogger(StartFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    
    public Color chooseColor(int color){
        switch(color){
            case 0 ->{
                return new Color(220,20,60); // red
            }
            case 1 ->{
                return new Color(138,43,226); // purple
            }
            case 2 ->{
                return Color.BLUE;
            }
            case 3 ->{
                return Color.GREEN;
            }
            case 4 ->{
                return Color.MAGENTA;
            }
            case 5 ->{
                return Color.ORANGE;
            }
            case 6 ->{
                return Color.PINK;
            }
            case 7 ->{
                return Color.CYAN;
            }
            case 8 ->{
                return Color.DARK_GRAY;
            }
            case 9 ->{
                return new Color(85, 107, 47); // weird green
            }
            
        }
        return null;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        etiquetaElegir = new javax.swing.JLabel();
        btEmpezar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Color Picker");

        etiquetaElegir.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        etiquetaElegir.setText("Jugador 1, elija su color de ficha:");

        btEmpezar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btEmpezar.setText("Start Game");
        btEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmpezarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btEmpezar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(etiquetaElegir)
                        .addComponent(jLabel1)))
                .addGap(55, 55, 55)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154)
                        .addComponent(etiquetaElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(270, 270, 270)
                        .addComponent(btEmpezar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmpezarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEmpezarActionPerformed

    
    
    public void setNumJugador(int numJugador) {

        this.numJugador = numJugador;
    }

    public void setLastPlayer(boolean lastPlayer) {
        this.lastPlayer = lastPlayer;
    }
    
    

    /**
     * @param args the command line arguments
     */
    public void setNick(String nick) {
        this.nick = nick;
        setTitle(nick);
    }
    
    public void recibirColor(String color) { //Método que recibe un color y actualiza la lista de colores elegidos. 
        coloresElegidos.addLast(color);
        currentPlayer++;
        etiquetaElegir.setText("Jugador " + currentPlayer + " elija su color de ficha:");
        System.out.println(nick + " recibió " + color);
        for(int i = 0; i < 10; i++) {
            if(color.equals(opcionArray[i].getBackground().toString())) {
                System.out.println("Color en posición: " + i); 
                opcionArray[i].setEnabled(false); }
        }
       }
       
    
    public void mandarColor(Color color) throws IOException {
        etiquetaElegir.setText("Jugador " + currentPlayer + " elija su color de ficha:");
        coloresElegidos.add(color.toString());
        cliente.salida.writeInt(1);
        cliente.salida.writeUTF(color.toString());
        if(lastPlayer) {
            cliente.salida.writeInt(2);
        }
    }

    public void setServer(MarioServer server) {
        this.server = server;
    }
    
    

    public Color getColor() {
        return color;
    }
    
    
    
    
   

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new StartFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(StartFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEmpezar;
    private javax.swing.JLabel etiquetaElegir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
