/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Progra;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.LinkedList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class sopaFrame extends javax.swing.JFrame {

    /**
     * Creates new form sopaFrame
     */
    public static int ANCHO = 41;
    public static  int ALTO =  30;
    private sopa sopa;
    private int tamaño;
    private char[][] matriz;
    JButton[][] buttonArray;
    private SopaTimeThread timeThread;
    public Tablero.Tablero tablero;
    
    public sopaFrame() {
        initComponents();
        sopa = new sopa();
        sopa.generarMatriz();
        tamaño = sopa.getTamaño();
        if(tamaño == 10) {
            ANCHO = 80;
            ALTO = 60;
        }
        if(tamaño == 15) {
            ANCHO = 55;
            ALTO = 40;
            }
        matriz = sopa.getMatriz();
        buttonArray = new JButton[tamaño][tamaño];
        generarCuadros();
        palabrasEncontrarTF.setText("Palabras a encontrar: " + sopa.getHorizontal() + "  " + sopa.getVertical() + "  " + sopa.getDiag1() + "  " + sopa.getDiag2());
        sopa.print();
        timeThread = new SopaTimeThread(this);
        timeThread.start();
    }
    

    
    public void generarCuadros() {
        for(int f = 0; f < tamaño; f++) {
            for(int c = 0; c < tamaño; c++) {
                buttonArray[f][c] = new JButton();
                jPanel1.add(buttonArray[f][c]);
                buttonArray[f][c].setBounds(c * ANCHO, f * ALTO, ANCHO, ALTO);
                buttonArray[f][c].setText(String.valueOf(matriz[f][c]));
                buttonArray[f][c].addActionListener((java.awt.event.ActionEvent evt) -> {
                    clickSobreBoton(evt);
                });
                buttonArray[f][c].setBackground(Color.white);
                    }
                
                }
        
            }
   public void clickSobreBoton(java.awt.event.ActionEvent evt) {
       JButton current = (JButton) evt.getSource();
       if(current.getBackground() == Color.white) {
           current.setBackground(Color.orange);
       }
       else if(current.getBackground() == Color.orange) {
           current.setBackground(Color.white);
       }
   }
   
   public void setTime(String time) {
       this.timetf.setText(time);
   }
   
   public void gameOver() {
       JOptionPane.showMessageDialog(this, "Tiempo cumplido. Ha perdido :(");
        tablero.gameEnded(1);
        this.dispose();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        palabrasEncontrarTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        timetf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), null));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 877, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        jTextField1.setBackground(jPanel1.getBackground());
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField1.setText("Sopa de letras");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        palabrasEncontrarTF.setText("Palabras a encontrar:");
        palabrasEncontrarTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabrasEncontrarTFActionPerformed(evt);
            }
        });

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        timetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timetfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(palabrasEncontrarTF, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timetf, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timetf, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palabrasEncontrarTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void palabrasEncontrarTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabrasEncontrarTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_palabrasEncontrarTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LinkedList<Punto> puntos = new LinkedList();
        for(int f = 0; f < tamaño; f++) {
            for(int c = 0; c < tamaño; c++) {
                if(buttonArray[f][c].getBackground() == Color.orange) {
                    Punto p = new Punto(f, c);
                    puntos.addLast(p);
                }
            }
        }
        if (puntos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ninguna letra");
        }
        else {
            String s = sopa.encontrarPalabra(puntos);
            if(s == "horizontal") {
                System.out.println(sopa.getHorizontal() + " encontrada");
                for(int i = 0; i < puntos.size(); i++)
                    buttonArray[puntos.get(i).getX()][puntos.get(i).getY()].setBackground(Color.green);
            }
            else if(s == "vertical") {
                System.out.println(sopa.getVertical() + " encontrada");
                for(int i = 0; i < puntos.size(); i++)
                    buttonArray[puntos.get(i).getX()][puntos.get(i).getY()].setBackground(Color.green);
            }
            else if(s == "diag1") {
                System.out.println(sopa.getDiag1() + " encontrada");
                for(int i = 0; i < puntos.size(); i++)
                    buttonArray[puntos.get(i).getX()][puntos.get(i).getY()].setBackground(Color.green);
            }
            else if(s == "diag2") {
                System.out.println(sopa.getDiag2() + " encontrada");
                for(int i = 0; i < puntos.size(); i++)
                    buttonArray[puntos.get(i).getX()][puntos.get(i).getY()].setBackground(Color.green);
            }
            else {
                System.out.println("incorrecto");
                JOptionPane.showMessageDialog(this, "Palabra incorrecta");
                for(int i = 0; i < puntos.size(); i++)
                    buttonArray[puntos.get(i).getX()][puntos.get(i).getY()].setBackground(Color.white);
            }
        }
        palabrasEncontrarTF.setText("Palabras a encontrar: " + sopa.getHorizontal() + "  " + sopa.getVertical() + "  " + sopa.getDiag1() + "  " + sopa.getDiag2());
        if(sopa.getHorizontal() == "" && sopa.getVertical() == "" && sopa.getDiag1() == "" && sopa.getDiag2() == "") {
            JOptionPane.showMessageDialog(this, "HA GANADO :)");
            tablero.gameEnded(1);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void timetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timetfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timetfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sopaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sopaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sopaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sopaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sopaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField palabrasEncontrarTF;
    private javax.swing.JTextField timetf;
    // End of variables declaration//GEN-END:variables
}
