/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Miscellaneous;

import Server.Client;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public class SorteoFrame extends javax.swing.JFrame {
    Server.Client cliente;
    int numJugador = 1;
    String nick;
    int currentPlayer = 1;
    int totalJugadores;
    
    
    /**
     * Creates new form SorteoFrame
     */
    public SorteoFrame() {
        initComponents();
        btContinuar.setEnabled(false);
    }

    public void setCliente(Client cliente) {
        this.cliente = cliente;
    }

    public void setNumJugador(int numJugador) {
        this.numJugador = numJugador;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
        this.setTitle(nick);
    }

    public void setCurrentPlayer(int currentPlayer) {
        this.currentPlayer = currentPlayer;
    }
    
    public void recibirResultado(int resultado, String name) {
        txaResultados.append(name + ": " + resultado + "\n");
        currentPlayer++;
        etiquetaCurrent.setText("Jugador " + currentPlayer + " lance los dados:");
        if(currentPlayer > totalJugadores) {
            btContinuar.setEnabled(true);
            etiquetaCurrent.setVisible(false);
        }
    }

    public void setTotalJugadores(int totalJugadores) {
        this.totalJugadores = totalJugadores;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btContinuar = new javax.swing.JButton();
        btDado = new javax.swing.JButton();
        btDado2 = new javax.swing.JButton();
        etiquetaCurrent = new javax.swing.JLabel();
        btLanzar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaResultados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Sorteo");

        btContinuar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btContinuar.setText("Continuar");
        btContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContinuarActionPerformed(evt);
            }
        });

        btDado.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        btDado.setText("1");

        btDado2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        btDado2.setText("1");

        etiquetaCurrent.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        etiquetaCurrent.setText("Jugador 1, tire los dados:");

        btLanzar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btLanzar.setText("Lanzar dados");
        btLanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLanzarActionPerformed(evt);
            }
        });

        txaResultados.setColumns(20);
        txaResultados.setRows(5);
        jScrollPane1.setViewportView(txaResultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btDado, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(btDado2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(btLanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(etiquetaCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaCurrent)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDado, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDado2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLanzar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jScrollPane1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContinuarActionPerformed
        if(numJugador == 1) {
            try {
                cliente.salida.writeInt(5);
            } catch (IOException ex) {
                Logger.getLogger(SorteoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            System.out.println("Solo el jugador 1 puede tomar este atajo");
        }
    }//GEN-LAST:event_btContinuarActionPerformed

    private void btLanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLanzarActionPerformed
        if(numJugador != currentPlayer) {
            return;
        }
        btLanzar.setEnabled(false);
        Thread thread = new Thread() {
            public void run() {
            try {
                Random random = new Random();
                int giros = random.nextInt(18) + 7;
                int numero = 1;
                for(int i = 0; i < giros; i++) {
                    sleep(80);
                    btDado.setText(String.valueOf(numero));
                    if(numero == 6) {
                        numero = 1;
                    }
                    else {
                        numero++;
                    }
                }
                btDado.setText(String.valueOf(numero));
                giros = random.nextInt(18) + 7;
                int numero2 = 1;
                for(int i = 0; i < giros; i++) {
                    sleep(100);
                    btDado2.setText(String.valueOf(numero2));
                    if(numero2 == 6) {
                        numero2 = 1;
                    }
                    else {
                        numero2++;
                    }
                }
                btDado2.setText(String.valueOf(numero2));
                
                int resultado = numero + numero2;
//                resultado = 18;
            try {
                cliente.salida.writeInt(7);
            } catch (IOException ex) {
                Logger.getLogger(SorteoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                cliente.salida.writeInt(resultado);
            } catch (IOException ex) {
                Logger.getLogger(SorteoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
                
            }
            catch (InterruptedException ex) {
                Logger.getLogger(SorteoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        };
        thread.start();

    }//GEN-LAST:event_btLanzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SorteoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SorteoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SorteoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SorteoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SorteoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btContinuar;
    private javax.swing.JButton btDado;
    private javax.swing.JButton btDado2;
    private javax.swing.JButton btLanzar;
    private javax.swing.JLabel etiquetaCurrent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaResultados;
    // End of variables declaration//GEN-END:variables
}
